# `Numpy` Library of python
### Numpy Library use website
# https://numpy.org/doc/stable/ 

In [1]:
import numpy as np

In [3]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [12]:
a2 = a[np.newaxis, :]
# a2 = a[ : , np.newaxis]
print(a2)
a2.shape
a.shape

[[0 1 2 3 4 5]]


(6,)

In [13]:
# 3D Array
a3 = a2[np.newaxis, :]
print(a3)
a3.shape

[[[0 1 2 3 4 5]]]


(1, 1, 6)

# Why do we need to make ARRAYS like 1D, 2D, 3D etc

In [16]:
aa = np.array([1,2,3,4,5,6,7])
b = np.array([(1,2,3,4,5,6), (1,2,3,4,5,6)])