# Numpy_04_Part

In [1]:
import numpy as np

In [5]:
#Array from Existing data
a = np.arange(0,225,5)
a

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190,
       195, 200, 205, 210, 215, 220])

In [10]:
a = np.array([1,2,3,4,5,6,7])
b = np.array([8,9,10,11,12,13,14])
c = np.hstack((a,b))
c
z = np.concatenate((a,b))
z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
z = z.reshape(2,7)
len(z)
z.ndim
z.shape

(2, 7)

In [4]:
# min, max, and sum
data = np.array([1.0, 2.0])
data * 1.6
data.max()
data.min()
data.sum()

3.0

In [9]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
a.sum()
a.min()
a.min(axis=0)


array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])