# SVD in `Python`

In [9]:
import numpy as np
import pandas as pd
np.random.seed(7)
# import random as rd
A =  np.random.rand(4,3)
A

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904]])

In [15]:
# lets apply svd
U, sigma, VT = np.linalg.svd(A)
print(U)
print(sigma)
print(VT)

[[-0.41612164 -0.68336782 -0.07602728 -0.5950387 ]
 [-0.66606353  0.09418072  0.68906561  0.2695885 ]
 [-0.21689145  0.71480349 -0.04791516 -0.66311252]
 [-0.57979329  0.11486685 -0.7191054   0.36542136]]
[1.97135056 0.5333572  0.30175165]
[[-0.46270033 -0.70275908 -0.54040548]
 [ 0.80923709 -0.58373682  0.06623189]
 [ 0.36199964  0.40667064 -0.83879393]]
