# Naive Bayes Algorithem

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.datasets import load_iris

In [4]:
iris = load_iris()
X = iris.data
y = iris.target
# train test split data
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=42)
# Model initialize
gnb = GaussianNB()
# train model
gnb.fit(X_train, y_train)
# predict
y_pred = gnb.predict(X_test)
# evaluate model
print("accuracy score", accuracy_score(y_test, y_pred))
print("Confusion Matrix", confusion_matrix(y_test, y_pred))
print("Classification Report", classification_report(y_test, y_pred))

accuracy score 0.9777777777777777
Confusion Matrix [[19  0  0]
 [ 0 12  1]
 [ 0  0 13]]
Classification Report               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.92      0.96        13
           2       0.93      1.00      0.96        13

    accuracy                           0.98        45
   macro avg       0.98      0.97      0.97        45
weighted avg       0.98      0.98      0.98        45



In [5]:
# Model initialize
mnb = MultinomialNB()
# train model
mnb.fit(X_train, y_train)
# predict
y_pred_2 = mnb.predict(X_test)
# evaluate model
print("accuracy score", accuracy_score(y_test, y_pred_2))
print("Confusion Matrix", confusion_matrix(y_test, y_pred_2))
print("Classification Report", classification_report(y_test, y_pred_2))

accuracy score 0.9555555555555556
Confusion Matrix [[19  0  0]
 [ 0 12  1]
 [ 0  1 12]]
Classification Report               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.92      0.92      0.92        13
           2       0.92      0.92      0.92        13

    accuracy                           0.96        45
   macro avg       0.95      0.95      0.95        45
weighted avg       0.96      0.96      0.96        45



In [ ]:
# Model initialize
mnb = MultinomialNB()
# train model
mnb.fit(X_train, y_train)
# predict
y_pred_2 = mnb.predict(X_test)
# evaluate model
print("accuracy score", accuracy_score(y_test, y_pred_2))
print("Confusion Matrix", confusion_matrix(y_test, y_pred_2))
print("Classification Report", classification_report(y_test, y_pred_2))