# Numpy `Extension`

In [1]:
import numpy as np

In [4]:
# Create an array
a = np.array([1,2,3,4,5,6,7,8,9,0])
a
a[-5]

6

In [9]:
 b = np.arange(0,12,2)
b[2]
c = b.reshape(2,3)
c = b.reshape(3,2)
c

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [20]:
c[(c<4) | (c>7)]

array([ 0,  2,  8, 10])

In [21]:
#Enlist Boolean opersators
&& = and
|| = or
! = not

# Array Fom existing data
### `From an other array`

In [25]:
a = np.arange(0,225,5)
print(a)
len(a)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175
 180 185 190 195 200 205 210 215 220]


45

In [28]:
array1 = a[40:45]
array1

array([200, 205, 210, 215, 220])

In [33]:
# stacking of arrays
a = np.array([1,2,3,4,5,6,7,])
b = np.array([8,9,10,11,12,13,14])
d = np.vstack((a,b))
d = np.hstack((a,b))
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])