---
# Matrices in `Numpy`
---

In [2]:
import numpy as np

In [3]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
# creating a matrix of big dimension
a = np.arange(0,100,2).reshape((5,10))
a

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [12]:
b1 = a[1:3,3:5]
b2 = a[3:,6:8]
b3 = a[2:,8:]

array([[56, 58],
       [76, 78],
       [96, 98]])

In [14]:
# have all rows and all columns
b = a[1:4,4:7]
b

array([[28, 30, 32],
       [48, 50, 52],
       [68, 70, 72]])

In [28]:
a.min(axis = 1)
a.max(axis=1)
a.sum(axis=1)

array([ 90, 290, 490, 690, 890])

In [34]:
m = np.arange(0,20,2).reshape(5,2)
print(m)
m + np.array([20,22])

[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]
 [16 18]]


array([[20, 24],
       [24, 28],
       [28, 32],
       [32, 36],
       [36, 40]])

In [37]:
np.vstack((m,np.array([42,44])))

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [42, 44]])

In [40]:
# FLip array
np.flip(m)
np.fliplr(m)
np.flipud(m)

array([[16, 18],
       [12, 14],
       [ 8, 10],
       [ 4,  6],
       [ 0,  2]])

In [ ]:
# Numoy Fundamentals for new when doing ML
